version: '3.1'

services:
  hey-project-php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      args:
        # # для VS Code:
        # XDEBUG_CLIENT_HOST: host.docker.internal
        XDEBUG_CLIENT_HOST: 172.26.0.1
        XDEBUG_CLIENT_PORT: 9000
    image: php-fpm
    restart: always
    volumes:
      - ../:/app
      - ./tmp:/tmp/tmp:rw
    working_dir: /app
    container_name: 'hey-project-php-fpm'
    hostname: 'localhost'
    networks:
      project-network:
        ipv4_address: 172.26.0.3
    environment:
      XDEBUG_CONFIG: client_host=172.26.0.1 client_port=9000 remote_enable=1
      PHP_IDE_CONFIG: serverName=localhost
      DEV: 1
    # # Параметр для запуска в VS Code
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  hey-project-nginx:
    image: nginx:1.15.0
    container_name: 'hey-project-nginx'
    working_dir: /app
    ports:
      - '23080:80'
      - '23081:81'
    networks:
      project-network:
        ipv4_address: 172.26.0.4
    restart: always
    volumes:
      - ../:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  hey-project-db:
    container_name: hey-project-db
    image: percona:8
    user: root
    restart: always
    command: ['mysqld', '--user=root', "--sql-mode=STRICT_TRANS_TABLES,ALLOW_INVALID_DATES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"]
    environment:
      MYSQL_DATABASE: hey-project
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - '23082:3306'
    volumes:
      - ../:/app
      - ./data/mysql:/var/lib/mysql:rw
    networks:
      project-network:
        ipv4_address: 172.26.0.5

  hey-project-rabbit-mq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    #image: rabbitmq:3.10.7-management
    working_dir: /app
    hostname: 'localhost'
    restart: always
    container_name: 'hey-project-rabbit-mq'
    networks:
      project-network:
        ipv4_address: 172.26.0.6
    ports:
      - '23672:15672'
      - '23673:5672'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
      RABBITMQ_DEFAULT_VHOST: '/'

volumes:
  mysql:
  hey-project-data: {}

networks:
  project-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
